export const FETCH_ALL_REFLECTIONS_PENDING = 'FETCH_ALL_REFLECTIONS_PENDING';
export const FETCH_ALL_REFLECTIONS_SUCCESS = 'FETCH_ALL_REFLECTIONS_SUCCESS';
export const FETCH_ALL_REFLECTIONS_FAILED = 'FETCH_ALL_REFLECTIONS_FAILED';

export const UPDATE_REFLECTION_PENDING = 'UPDATE_REFLECTION_PENDING';
export const UPDATE_REFLECTION_SUCCESS = 'UPDATE_REFLECTION_SUCCESS';
export const UPDATE_REFLECTION_FAILED = 'UPDATE_REFLECTION_FAILED';
